//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassTemplateGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MassTemplateGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;ClientData&gt;
        ///    &lt;Client Account=&quot;58871298720&quot;&gt;Jo Berger&lt;/Client&gt;
        ///    &lt;Client Account=&quot;85993673005&quot;&gt;Kristen Thomas&lt;/Client&gt;
        ///    &lt;Client Account=&quot;15547305019&quot;&gt;Robert Cole&lt;/Client&gt;
        ///    &lt;Client Account=&quot;59190971862&quot;&gt;Sara Mcgrath&lt;/Client&gt;
        ///    &lt;Client Account=&quot;68521559184&quot;&gt;Charles Nguyen&lt;/Client&gt;
        ///    &lt;Client Account=&quot;98359295593&quot;&gt;Tonya Chan&lt;/Client&gt;
        ///    &lt;Client Account=&quot;80462603888&quot;&gt;Eric Hammond&lt;/Client&gt;
        ///    &lt;Client Account=&quot;38693081858&quot;&gt;Christopher Whitaker&lt;/Client&gt;
        ///    &lt;C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bhdldata {
            get {
                return ResourceManager.GetString("bhdldata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es-do&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;Readme&quot;&gt;
        ///    &lt;title&gt;Generador de Archivos para Cargas Masivas de Registros, Internet Banking Empresarial BHD Le&amp;oacute;n&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdn.jsdelivr.net/npm/normalize.css@8.0.1/normalize.css&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            padding: 20px;
        ///            font-family: Helvetica, Verdana, sans-serif;
        ///            overflow-y: scroll;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string chlog {
            get {
                return ResourceManager.GetString("chlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;ClientData&gt;
        ///    &lt;Client ID=&quot;25096625784&quot;&gt;Steven Cruz&lt;/Client&gt;
        ///    &lt;Client ID=&quot;52941510832&quot;&gt;Paul Hendrix&lt;/Client&gt;
        ///    &lt;Client ID=&quot;84860887742&quot;&gt;Steven Guzman&lt;/Client&gt;
        ///    &lt;Client ID=&quot;98491815190&quot;&gt;Daniel Higgins&lt;/Client&gt;
        ///    &lt;Client ID=&quot;05222271165&quot;&gt;Ashley White&lt;/Client&gt;
        ///    &lt;Client ID=&quot;18619493800&quot;&gt;Maurice Guerrero&lt;/Client&gt;
        ///    &lt;Client ID=&quot;98645298849&quot;&gt;Steven Schultz&lt;/Client&gt;
        ///    &lt;Client ID=&quot;03699585735&quot;&gt;Curtis Hardin&lt;/Client&gt;
        ///    &lt;Client ID=&quot;66776918111&quot;&gt;Barbara Morris [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string externalclients {
            get {
                return ResourceManager.GetString("externalclients", resourceCulture);
            }
        }
    }
}
