//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassTemplateGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AppFirstRun {
            get {
                return ((bool)(this["AppFirstRun"]));
            }
            set {
                this["AppFirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double AppMaxCashValue {
            get {
                return ((double)(this["AppMaxCashValue"]));
            }
            set {
                this["AppMaxCashValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Nomina_TargetRNG {
            get {
                return ((bool)(this["Nomina_TargetRNG"]));
            }
            set {
                this["Nomina_TargetRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NOMBRE NOMINA")]
        public string Nomina_Beneficiario {
            get {
                return ((string)(this["Nomina_Beneficiario"]));
            }
            set {
                this["Nomina_Beneficiario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Nomina_RefTrxRNG {
            get {
                return ((bool)(this["Nomina_RefTrxRNG"]));
            }
            set {
                this["Nomina_RefTrxRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RefTrxN001")]
        public string Nomina_RefTrx {
            get {
                return ((string)(this["Nomina_RefTrx"]));
            }
            set {
                this["Nomina_RefTrx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Nomina_ValueRNG {
            get {
                return ((bool)(this["Nomina_ValueRNG"]));
            }
            set {
                this["Nomina_ValueRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Nomina_Monto {
            get {
                return ((double)(this["Nomina_Monto"]));
            }
            set {
                this["Nomina_Monto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CONCEPTO NOMINA")]
        public string Nomina_Concepto {
            get {
                return ((string)(this["Nomina_Concepto"]));
            }
            set {
                this["Nomina_Concepto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Nomina_Email {
            get {
                return ((string)(this["Nomina_Email"]));
            }
            set {
                this["Nomina_Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EfeCaja_TargetRNG {
            get {
                return ((bool)(this["EfeCaja_TargetRNG"]));
            }
            set {
                this["EfeCaja_TargetRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string EfeCaja_TipoID {
            get {
                return ((string)(this["EfeCaja_TipoID"]));
            }
            set {
                this["EfeCaja_TipoID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NOMBRE EFECTIVO EN CAJA")]
        public string EfeCaja_Beneficiario {
            get {
                return ((string)(this["EfeCaja_Beneficiario"]));
            }
            set {
                this["EfeCaja_Beneficiario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EfeCaja_ValueRNG {
            get {
                return ((bool)(this["EfeCaja_ValueRNG"]));
            }
            set {
                this["EfeCaja_ValueRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double EfeCaja_Monto {
            get {
                return ((double)(this["EfeCaja_Monto"]));
            }
            set {
                this["EfeCaja_Monto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CONCEPTO EFECTIVO EN CAJA")]
        public string EfeCaja_Concepto {
            get {
                return ((string)(this["EfeCaja_Concepto"]));
            }
            set {
                this["EfeCaja_Concepto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I")]
        public string EfeCaja_Registro {
            get {
                return ((string)(this["EfeCaja_Registro"]));
            }
            set {
                this["EfeCaja_Registro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EfeCaja_Email {
            get {
                return ((string)(this["EfeCaja_Email"]));
            }
            set {
                this["EfeCaja_Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CkAdm_TargetRNG {
            get {
                return ((bool)(this["CkAdm_TargetRNG"]));
            }
            set {
                this["CkAdm_TargetRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NOMBRE CK ADM")]
        public string CkAdm_Beneficiario {
            get {
                return ((string)(this["CkAdm_Beneficiario"]));
            }
            set {
                this["CkAdm_Beneficiario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CkAdm_ValueRNG {
            get {
                return ((bool)(this["CkAdm_ValueRNG"]));
            }
            set {
                this["CkAdm_ValueRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double CkAdm_Monto {
            get {
                return ((double)(this["CkAdm_Monto"]));
            }
            set {
                this["CkAdm_Monto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DESCRIPCION CK ADM")]
        public string CkAdm_Descripcion {
            get {
                return ((string)(this["CkAdm_Descripcion"]));
            }
            set {
                this["CkAdm_Descripcion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01")]
        public string CkAdm_Sucursal {
            get {
                return ((string)(this["CkAdm_Sucursal"]));
            }
            set {
                this["CkAdm_Sucursal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CkAdm_Email {
            get {
                return ((string)(this["CkAdm_Email"]));
            }
            set {
                this["CkAdm_Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BCCk_AcctRNG {
            get {
                return ((bool)(this["BCCk_AcctRNG"]));
            }
            set {
                this["BCCk_AcctRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80950734261")]
        public string BCCk_Cuenta {
            get {
                return ((string)(this["BCCk_Cuenta"]));
            }
            set {
                this["BCCk_Cuenta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BCCk_ValueRNG {
            get {
                return ((bool)(this["BCCk_ValueRNG"]));
            }
            set {
                this["BCCk_ValueRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double BCCk_Monto {
            get {
                return ((double)(this["BCCk_Monto"]));
            }
            set {
                this["BCCk_Monto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BCCk_TargetRNG {
            get {
                return ((bool)(this["BCCk_TargetRNG"]));
            }
            set {
                this["BCCk_TargetRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BENEFICIARIO BLOQ Y CONF CK")]
        public string BCCk_Beneficiario {
            get {
                return ((string)(this["BCCk_Beneficiario"]));
            }
            set {
                this["BCCk_Beneficiario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CONCEPTO BLOQ Y CONF CK")]
        public string BCCk_Concepto {
            get {
                return ((string)(this["BCCk_Concepto"]));
            }
            set {
                this["BCCk_Concepto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OBSERVACIONES BLOQ Y CONF CHEQUE")]
        public string BCCk_Observaciones {
            get {
                return ((string)(this["BCCk_Observaciones"]));
            }
            set {
                this["BCCk_Observaciones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TBHD_TargetRNG {
            get {
                return ((bool)(this["TBHD_TargetRNG"]));
            }
            set {
                this["TBHD_TargetRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BENEFICIARIO TBHDL")]
        public string TBHD_Beneficiario {
            get {
                return ((string)(this["TBHD_Beneficiario"]));
            }
            set {
                this["TBHD_Beneficiario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TBHD_RefTrxRNG {
            get {
                return ((bool)(this["TBHD_RefTrxRNG"]));
            }
            set {
                this["TBHD_RefTrxRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RefTrxBHD1")]
        public string TBHD_RefTrx {
            get {
                return ((string)(this["TBHD_RefTrx"]));
            }
            set {
                this["TBHD_RefTrx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TBHD_ValueRNG {
            get {
                return ((bool)(this["TBHD_ValueRNG"]));
            }
            set {
                this["TBHD_ValueRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double TBHD_Monto {
            get {
                return ((double)(this["TBHD_Monto"]));
            }
            set {
                this["TBHD_Monto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DESCRIPCION TBHDL")]
        public string TBHD_Descripcion {
            get {
                return ((string)(this["TBHD_Descripcion"]));
            }
            set {
                this["TBHD_Descripcion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CA")]
        public string TBHD_TipoCta {
            get {
                return ((string)(this["TBHD_TipoCta"]));
            }
            set {
                this["TBHD_TipoCta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TBHD_Email {
            get {
                return ((string)(this["TBHD_Email"]));
            }
            set {
                this["TBHD_Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TBHD_Fax {
            get {
                return ((string)(this["TBHD_Fax"]));
            }
            set {
                this["TBHD_Fax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TBHD_RefDebito {
            get {
                return ((string)(this["TBHD_RefDebito"]));
            }
            set {
                this["TBHD_RefDebito"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ACH_AcctRNG {
            get {
                return ((bool)(this["ACH_AcctRNG"]));
            }
            set {
                this["ACH_AcctRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("782514533")]
        public string ACH_NumCta {
            get {
                return ((string)(this["ACH_NumCta"]));
            }
            set {
                this["ACH_NumCta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BPD")]
        public string ACH_Banco {
            get {
                return ((string)(this["ACH_Banco"]));
            }
            set {
                this["ACH_Banco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CA")]
        public string ACH_TipoCta {
            get {
                return ((string)(this["ACH_TipoCta"]));
            }
            set {
                this["ACH_TipoCta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ACH_TargetRNG {
            get {
                return ((bool)(this["ACH_TargetRNG"]));
            }
            set {
                this["ACH_TargetRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BENEFICIARIO ACH")]
        public string ACH_Beneficiario {
            get {
                return ((string)(this["ACH_Beneficiario"]));
            }
            set {
                this["ACH_Beneficiario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string ACH_TipoMov {
            get {
                return ((string)(this["ACH_TipoMov"]));
            }
            set {
                this["ACH_TipoMov"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ACH_RefTrxRNG {
            get {
                return ((bool)(this["ACH_RefTrxRNG"]));
            }
            set {
                this["ACH_RefTrxRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RefTrxACH1")]
        public string ACH_RefTrx {
            get {
                return ((string)(this["ACH_RefTrx"]));
            }
            set {
                this["ACH_RefTrx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ACH_ValueRNG {
            get {
                return ((bool)(this["ACH_ValueRNG"]));
            }
            set {
                this["ACH_ValueRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double ACH_Monto {
            get {
                return ((double)(this["ACH_Monto"]));
            }
            set {
                this["ACH_Monto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DESCRIPCION ACH")]
        public string ACH_Descripcion {
            get {
                return ((string)(this["ACH_Descripcion"]));
            }
            set {
                this["ACH_Descripcion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ACH_Email {
            get {
                return ((string)(this["ACH_Email"]));
            }
            set {
                this["ACH_Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ACH_Fax {
            get {
                return ((string)(this["ACH_Fax"]));
            }
            set {
                this["ACH_Fax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LBTR_AcctRNG {
            get {
                return ((bool)(this["LBTR_AcctRNG"]));
            }
            set {
                this["LBTR_AcctRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("782514533")]
        public string LBTR_NumCta {
            get {
                return ((string)(this["LBTR_NumCta"]));
            }
            set {
                this["LBTR_NumCta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BPDODOSXXXX")]
        public string LBTR_Banco {
            get {
                return ((string)(this["LBTR_Banco"]));
            }
            set {
                this["LBTR_Banco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CA")]
        public string LBTR_TipoCta {
            get {
                return ((string)(this["LBTR_TipoCta"]));
            }
            set {
                this["LBTR_TipoCta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BENEFICIARIO LBTR")]
        public string LBTR_Beneficiario {
            get {
                return ((string)(this["LBTR_Beneficiario"]));
            }
            set {
                this["LBTR_Beneficiario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string LBTR_TipoMov {
            get {
                return ((string)(this["LBTR_TipoMov"]));
            }
            set {
                this["LBTR_TipoMov"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LBTR_RefTrxRNG {
            get {
                return ((bool)(this["LBTR_RefTrxRNG"]));
            }
            set {
                this["LBTR_RefTrxRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RefTrxBC01")]
        public string LBTR_RefTrx {
            get {
                return ((string)(this["LBTR_RefTrx"]));
            }
            set {
                this["LBTR_RefTrx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LBTR_ValueRNG {
            get {
                return ((bool)(this["LBTR_ValueRNG"]));
            }
            set {
                this["LBTR_ValueRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double LBTR_Monto {
            get {
                return ((double)(this["LBTR_Monto"]));
            }
            set {
                this["LBTR_Monto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DESCRIPCION LBTR")]
        public string LBTR_Descripcion {
            get {
                return ((string)(this["LBTR_Descripcion"]));
            }
            set {
                this["LBTR_Descripcion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LBTR_Email {
            get {
                return ((string)(this["LBTR_Email"]));
            }
            set {
                this["LBTR_Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LBTR_Fax {
            get {
                return ((string)(this["LBTR_Fax"]));
            }
            set {
                this["LBTR_Fax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string LBTR_TipoID {
            get {
                return ((string)(this["LBTR_TipoID"]));
            }
            set {
                this["LBTR_TipoID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LBTR_TargetRNG {
            get {
                return ((bool)(this["LBTR_TargetRNG"]));
            }
            set {
                this["LBTR_TargetRNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27805051883")]
        public string Nomina_Cuenta {
            get {
                return ((string)(this["Nomina_Cuenta"]));
            }
            set {
                this["Nomina_Cuenta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25870663238")]
        public string EfeCaja_ID {
            get {
                return ((string)(this["EfeCaja_ID"]));
            }
            set {
                this["EfeCaja_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("02416278042")]
        public string TBHD_NumCta {
            get {
                return ((string)(this["TBHD_NumCta"]));
            }
            set {
                this["TBHD_NumCta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17159545790")]
        public string LBTR_ID {
            get {
                return ((string)(this["LBTR_ID"]));
            }
            set {
                this["LBTR_ID"] = value;
            }
        }
    }
}
